
S=src/
I=inc/ ../include/
O=obj/

CXX = c++ -std=c++98
MODEFLAGS = $(if $(filter std-%,$(TARGET)), -DUSE_STD)
CXXFLAGS = $(MODEFLAGS) -Wextra -Werror -Wall -pedantic $(I:%=-I %)
MDKEY = $(CXX) $(MODEFLAGS)

LD = c++
LDFLAGS =

NAME += std-tester ft-tester
#NAME += benchmark

define SRC
$Smain.cpp
endef

define UNUSED
endef

